#!/bin/bash
### BEGIN INIT INFO
# Provides:				SSG
# Required-Start:		$remote_fs $syslog
# Required-Stop:		$remote_fs $syslog
# Default-Start:		2 3 4 5
# Default-Stop: 		0 1 6
# Short-Description:	ShadowsocksGO
# Description:			Enable service provided by SSG
### END INIT INFO

start()
{
	str=$"\n"
	nohup /usr/local/orchard/outline-ss-server --config /usr/local/orchard/config.yml &
	sstr=$(echo -e $str)
	echo $sstr
	echo 'ShadowsocksGO START OK'
}

stop()
{
	p=$(pidof outline-ss-server)
	kill -9 $p
	echo 'ShadowsocksGO STOP OK'
}

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
restart)
	stop
	start
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 0
	;;
esac
exit 0
