#!/bin/bash
### BEGIN INIT INFO
# Provides:             orchard
# Required-Start:       $local_fs $network
# Required-Stop:        $local_fs
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Orchard Watch
# Description:          Orchard Watch Service
### END INIT INFO

filepath="/usr/local/orchard/watch.py"

start(){
    nohup python3 $filepath>/root/log_orchard &
    echo 'Orchard Watch START OK'
}

stop(){
    serverpid=`ps -aux|grep "$filepath"|grep -v grep|awk '{print $2}'`
    kill -9 $serverpid
    echo 'Orchard Watch STOP OK'
}

restart(){
    stop
    start
}

case $1 in
start)
    start
    ;;
stop)
    stop
    ;;
restart)
    restart
    ;;
*)
    echo "Usage: $0 {start|stop|restart}"
    exit 0
    ;;
esac
exit 0